// Fixed wording of the printed document, in the document's language (not the interface language): these are the legal titles
// and phrases an Israeli חשבון עסקה / קבלה / חשבונית מס and a US invoice carry. Keys mirror each other.
import type { Kind } from "../../invoices.ts";

const he = {
  kind: { invoice: "חשבונית", bill: "חשבון עסקה", receipt: "קבלה", tax: "חשבונית מס" } as Record<Kind, string>,
  draft: "טיוטה",
  paidMark: "שולם",
  original: "מקור",
  copy: "העתק",
  patur: "עוסק פטור מס׳",
  murshe: "עוסק מורשה מס׳",
  companyNo: "ח.פ.",
  phone: "טלפון",
  number: "מספר",
  date: "תאריך",
  due: "לתשלום עד",
  to: "לכבוד",
  forRef: (doc: string, ref: string) => `בגין ${doc} מס׳ ${ref}`,
  desc: "תיאור",
  qty: "כמות",
  price: "מחיר ליחידה",
  amount: "סה״כ",
  net: "סה״כ לפני מע״מ",
  vat: "מע״מ",
  totalReceived: "סה״כ התקבל",
  totalDue: "סה״כ לתשלום",
  totalDueCur: (_c: string) => "סה״כ לתשלום",
  method: "אמצעי תשלום",
  paidInFull: (d: string) => `שולם במלואו${d ? ` בתאריך ${d}` : ""}. תודה.`,
  pay: "לתשלום",
  by: "עד",
  notes: "הערות",
  exempt: "עוסק פטור — העסקה פטורה ממע״מ ולא נגבה מע״מ. מסמך זה אינו חשבונית מס. ",
  zeroRated: "מע״מ בשיעור אפס. ",
  billNotReceipt: "חשבון עסקה אינו מהווה קבלה; קבלה תונפק עם קבלת התשלום.",
  billNotTax: "חשבון עסקה אינו חשבונית מס; חשבונית מס תונפק עם קבלת התשלום.",
  sign: "חתימה",
};
type Words = typeof he;

const en: Words = {
  kind: { invoice: "Invoice", bill: "Payment request", receipt: "Receipt", tax: "Tax invoice" },
  draft: "DRAFT",
  paidMark: "PAID",
  original: "Original",
  copy: "Copy",
  patur: "VAT-exempt dealer no.",
  murshe: "VAT reg. no.",
  companyNo: "Company no.",
  phone: "Phone",
  number: "No.",
  date: "Date",
  due: "Due",
  to: "Bill to",
  forRef: (doc, ref) => `For ${doc.toLowerCase()} no. ${ref}`,
  desc: "Description",
  qty: "Qty",
  price: "Unit price",
  amount: "Amount",
  net: "Subtotal",
  vat: "VAT",
  totalReceived: "Total received",
  totalDue: "Total due",
  totalDueCur: (c) => `Total due (${c})`,
  method: "Payment method",
  paidInFull: (d) => `Paid in full${d ? ` on ${d}` : ""}. Thank you.`,
  pay: "Please pay",
  by: "by",
  notes: "Payment details & notes",
  exempt: "VAT-exempt dealer (osek patur): no VAT charged. This document is not a tax invoice. ",
  zeroRated: "VAT at 0%. ",
  billNotReceipt: "This payment request is not a receipt; a receipt is issued when payment arrives.",
  billNotTax: "This payment request is not a tax invoice; a tax invoice is issued when payment arrives.",
  sign: "Signature",
};

export const L = { he, en };
/** Payment methods are stored in Hebrew (the Israeli receipt's wording); the English version translates them. */
export const METHOD_EN: Record<string, string> = {
  "העברה בנקאית": "Bank transfer",
  ביט: "Bit",
  מזומן: "Cash",
  "צ'ק": "Check",
  "כרטיס אשראי": "Credit card",
};
