<script lang="ts">
  // The official Form 1301 pages with the year's values placed on them (old web/src/views/Print.svelte, mode "form").
  // Page images and box positions ship with the IL pack (packages/countries/il/form), extracted from the official PDF by layout.py.
  // A fixed Hebrew form: marks are placed with physical left offsets, independent of the interface direction.
  import { page } from "$app/state";
  import { S } from "#lib/stores/books.svelte.ts";
  import { t } from "#lib/i18n.svelte.ts";
  import { Button } from "#lib/ui/index.ts";
  import { ilYear } from "../../../tax/il/il.ts";
  import layoutJson from "@openbooks/country-il/form/layout.json";
  import p1 from "@openbooks/country-il/form/p-1.png";
  import p2 from "@openbooks/country-il/form/p-2.png";
  import p3 from "@openbooks/country-il/form/p-3.png";
  import p4 from "@openbooks/country-il/form/p-4.png";
  import { marks, type Layout } from "./marks.ts";
  import "../../print.css";

  const year = $derived(+page.params.year! || S.year);
  const b = $derived(S.data ? ilYear(year) : null);
  const layout = layoutJson as unknown as Layout; // generated by layout.py; JSON widens the tuple and enum types
  const pages = [p1, p2, p3, p4];
</script>

<svelte:head><title>1301 · {year} · OpenBooks</title></svelte:head>

<div class="ob-print">
  <div class="ob-print-bar"><Button variant="primary" icon="printer" onclick={() => print()}>{t("print.button")}</Button></div>
  {#if b}
    <div class="form-scroll" dir="rtl" lang="he">
      {#each pages as img, n (img)}
        <div class="form-page" style:width="{layout.size[0]}pt" style:height="{layout.size[1]}pt" style:background-image="url({img})">
          {#each marks(layout, n + 1, b.v) as mk, i (i)}
            <span class="mk {mk.cls}" dir={mk.cls === "txt" ? "auto" : undefined} style={mk.style}>{mk.text}</span>
          {/each}
        </div>
      {/each}
    </div>
  {/if}
</div>
